name: Go
on:
  push
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: test
        run: |
          make
